managym-app/board/urls.py
from django.urls import path

from . import views

app_name = 'board'
urlpatterns = [
	path('', views.BoardListView.as_view(), name='board'),
    path('athletes/', views.AthleteListView.as_view(), name='athlete-list'),
    path('athlete/<int:athlete_id>/', views.AthleteDetailView.as_view(), name='athlete-detail'),
    path('athlete/<int:athlete_id>/new_target/', views.athlete_new_target,\
    	name='athlete-new-target'),
    path('athlete/<int:athlete_id>/update_target/', views.athlete_update_target,\
    	name='athlete-update-target'),
    path('athlete/<int:athlete_id>/save_information/', views.athlete_save_information,\
    	name='athlete-save-information'),
    path('athlete/<int:athlete_id>/data_graph/', views.athlete_graph_get_data,\
    	name='athlete-graph-get-data'),
]

managym-app/managym/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

from board import views

urlpatterns = [
	path('', views.index, name='index'),
	path('board/', include('board.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

managym-app/templates/base.html
{% load static %}<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Custom Css -->
    {% block stylesheet %}{% endblock %}

    <!-- Icons Font Awesome -->
    <script src="https://kit.fontawesome.com/ff43bb3ee5.js" crossorigin="anonymous"></script>

    <title>{% block title %}Managym{% endblock %}</title>
  </head>
  <body>
    {% block body %}

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <span class="navbar-brand mb-0 h1">Managym</span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url "board:board" %}"><i class="fas fa-home"></i> {{ _('My group') }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "board:athlete-list" %}"><i class="fas fa-users "></i> {{ _('Athletes') }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"><i class="fas fa-book "></i> {{ _('Presence') }}</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
          {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> {{ _('Log out') }}</a>
          {% else %}
            <a class="nav-link" href="{% url 'login' %}"><i class="fas fa-sign-in-alt"></i> {{ _('Log in') }}</a>
          {% endif %}
          </li>
        </ul>
      </div>
    </nav>

    <div class="container">
      <!--<div class="alert alert-info" role="alert">{% block message %}{% endblock %}</div>-->

    {# app content need to be provided in app_content block #}
    {% block content %}{% endblock %}
    </div>
    {% endblock %}
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"</script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- ChartJS, then simditor for ChartJS -->
    <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js'></script>
    <!--<script src='https://cdnjs.cloudflare.com/ajax/libs/simditor/2.3.28/lib/simditor.min.js'></script>-->
    <script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js'></script>
    <script src="{% static 'js/token.js' %}"></script>
    {% block javascript %}{% endblock %}
  </body>
</html>

managym-app/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Log in</h3>
          {% if form.errors %}
          <p>Your username and password didn't match. Please try again.</p>
          {% endif %}

          {% if next %}
            {% if user.is_authenticated %}
            <p>Your account doesn't have access to this page. To proceed,
            please login with an account that has access.</p>
            {% else %}
            <p>Please login to see this page.</p>
            {% endif %}
          {% endif %}
          <form method="post" action="{% url 'login' %}">
          {% csrf_token %}
            <table>
            <tr>
              <td>{{ form.username.label_tag }}</td>
              <td>{{ form.username }}</td>
            </tr>
            <tr>
              <td>{{ form.password.label_tag }}</td>
              <td>{{ form.password }}</td>
            </tr>
            </table>
            <input type="submit" value="login">
            <input type="hidden" name="next" value="{{ next }}">
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}