managym-app/board/urls.py
from django.urls import path

from . import views

app_name = 'board'
urlpatterns = [
	path('', views.BoardListView.as_view(), name='board'),
    path('athletes/', views.AthleteListView.as_view(), name='athlete-list'),
    path('athlete/<int:athlete_id>/', views.AthleteDetailView.as_view(), name='athlete-detail'),
    path('athlete/<int:athlete_id>/new_target/', views.athlete_new_target,\
    	name='athlete-new-target'),
    path('athlete/<int:athlete_id>/update_target/', views.athlete_update_target,\
    	name='athlete-update-target'),
    path('athlete/<int:athlete_id>/save_information/', views.athlete_save_information,\
    	name='athlete-save-information'),
    path('athlete/<int:athlete_id>/data_graph/', views.athlete_graph_get_data,\
    	name='athlete-graph-get-data'),
]

managym-app/managym/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

from board import views

urlpatterns = [
	path('', views.index, name='index'),
	path('board/', include('board.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

managym-app/athletes/models.py
from django.db import models
from django.contrib.auth.models import User
from dj.choices import Choices, Choice


class TargetResult(models.Model):
    """Model representing the target/results for an athlete on an event on an apparatus."""

    athlete = models.ForeignKey('Athlete', on_delete=models.DO_NOTHING)
    apparatus = models.ForeignKey('Apparatus', on_delete=models.DO_NOTHING)
    event = models.ForeignKey('Event', on_delete=models.DO_NOTHING)
    target_sv = models.FloatField(null=True, blank=True)
    target_ex = models.FloatField(null=True, blank=True)
    result_sv = models.FloatField(null=True, blank=True)
    result_ex = models.FloatField(null=True, blank=True)

    class Meta:
        verbose_name = "TargetResult"
        verbose_name_plural = "TargetsResults"

    def __str__(self):
        return f'{self.athlete} - {self.event} - {self.apparatus}'
    

class Gender(Choices):
    male = Choice("male")
    female = Choice("female")
    not_specified = Choice("not specified")

class Athlete(models.Model):
    """Model representing an athlete."""

    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    gender = models.IntegerField(choices=Gender(),
                                 default=Gender.not_specified.id)
    birth_date = models.DateField()
    email = models.EmailField(max_length=100)
    email_2 = models.EmailField(max_length=100, null=True, blank=True)
    phone_number = models.CharField(max_length=15, null=True, blank=True)
    phone_number_2 = models.CharField(max_length=15, null=True, blank=True)
    address = models.CharField(max_length=64, null=True, blank=True)
    city = models.CharField(max_length=64, null=True, blank=True)
    province = models.CharField(max_length=2, null=True, blank=True)
    postal_code = models.CharField(max_length=10, null=True, blank=True)
    group = models.ForeignKey('Group', on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        verbose_name = "Athlete"
        verbose_name_plural = "Athletes"

    def __str__(self):
        """String for representing the Athlete object."""
        return f'{self.first_name} {self.last_name}'

    def picture(self, size):
        email = self.email or 'email@test.com'
        digest = md5(email.lower().encode('utf-8')).hexdigest()
        return f'https://www.gravatar.com/avatar/{digest}?d=identicon&s={size}'

class Group(models.Model):
    """Model representing a group of athletes."""

    name = models.CharField(max_length=120, default="New group")
    users = models.ManyToManyField(User, related_name='groups_of_athletes')

    class Meta:
        verbose_name = "Group of athletes"
        verbose_name_plural = "Groups of athletes"

    def __str__(self):
        return self.name
    
    
class Apparatus(models.Model):
    """Model representing an apparatus."""

    short_name = models.CharField(max_length=3, unique=True)
    name = models.CharField(max_length=30, unique=True)

    class Meta:
        verbose_name = "Apparatus"
        verbose_name_plural = "Apparatus"

    def __str__(self):
        return self.name

class Event(models.Model):
    """Model representing an event."""

    name = models.CharField(max_length=100)
    description = models.CharField(max_length=140, null=True, blank=True)
    date = models.DateField()
    place= models.CharField(max_length=120, null=True)
    type = models.ForeignKey('TypeEvent', on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        verbose_name = "Event"
        verbose_name_plural = "Events"

    def __str__(self):
        return self.name

class TypeEvent(models.Model):
    """Model representing the type of an event."""

    name = models.CharField(max_length=64)

    class Meta:
        verbose_name = "TypeEvent"
        verbose_name_plural = "TypesEvent"

    def __str__(self):
        return self.name

class Information(models.Model):
    """Model representing an information."""

    body = models.TextField(max_length=1000)
    timestamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    type = models.ForeignKey('TypeInformation', on_delete=models.DO_NOTHING)
    athlete = models.ForeignKey('Athlete', on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Information"
        verbose_name_plural = "Information"

    def __str__(self):
        return self.body
    
class TypeInformation(models.Model):
    """Model representing a type on information."""

    name = models.CharField(max_length=64)

    class Meta:
        verbose_name = "TypeInformation"
        verbose_name_plural = "TypesInformation"

    def __str__(self):
        return self.name
    
    
    
    

managym-app/board/forms.py
from django import forms

from .models import Event, Information

class NewTargetForm(forms.Form):
    """Form representing all event without target"""
    event = forms.ModelChoiceField(queryset=None)


class SaveInformationForm(forms.Form):
    """
    Form representing a new/edit information
    """
    body = forms.CharField(
        widget=forms.Textarea(
            attrs={'placeholder': 'Write your text, you\'re limited to 1000 characters',
            	   'class': 'form-control'}
        	),
        max_length=1000,
    )
    information_id = forms.CharField(
        widget=forms.TextInput(
            attrs={'type': 'hidden',
                   'id': 'id_information'}
            )
        )
    information_type = forms.CharField(
        widget=forms.TextInput(
            attrs={'type': 'hidden',
                    'id': 'type_information'}
            )
        )

managym-app/board/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.utils import timezone
from django.db.models import Sum, F, Q

from .models import Athlete, Event, TargetResult, Round2, Information,\
    TypeInformation
from .forms import NewTargetForm, SaveInformationForm

def index(request):
    return render(request, 'board/index.html', {})

@method_decorator(login_required, name='dispatch')
class BoardListView(ListView):
    context_object_name = 'athletes'
    template_name = 'board/board.html'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context

    def get_queryset(self):
        queryset = Athlete.objects.filter(
            group__trainers__id=self.request.user.pk).order_by('first_name', 'last_name')
        return queryset

@method_decorator(login_required, name='dispatch')
class AthleteListView(ListView):
    # model = Athlete
    context_object_name = 'athletes'
    template_name = 'board/athletes.html'
    paginate_by = 20

    def get_queryset(self):
        query_list = self.request.GET.get('q')
        if query_list:
            query = Q()
            for item in query_list.split():
                query = query | Q(first_name__icontains=item) | Q(last_name__icontains=item)
            result = Athlete.objects.filter(query)
        else:
            result = Athlete.objects
        return result.order_by('first_name', 'last_name')


@method_decorator(login_required, name='dispatch')
class AthleteDetailView(DetailView):
    model = Athlete
    context_object_name = 'athlete'
    pk_url_kwarg = 'athlete_id' 

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        athlete = self.get_object()
        events_participated = Event.objects.filter(targetresult__athlete=athlete).distinct().all()
        for event in events_participated:
            event.targets_results = TargetResult.objects.filter(athlete=athlete, event=event).values(\
                'target_sv', 'target_ex', 'result_sv', 'result_ex', 'apparatus__id', 'apparatus__name')
        context['events_participated'] = events_participated
        new_target_form = NewTargetForm()
        new_target_form.fields['event'].queryset = Event.objects.exclude(
            targetresult__athlete=athlete).distinct()
        context['new_target_form'] = new_target_form
        context['new_information_form'] = SaveInformationForm()
        return context


@login_required
def athlete_new_target(request, athlete_id):
    if request.method == 'POST':
        athlete = get_object_or_404(Athlete, pk=athlete_id)
        event_id = request.POST.get('event')
        # Male apparatus: 1=floor, 2=pommel horse, 3=rings, 4=vault, 5=parallel bars, 6=high bar
        if athlete.gender == 1:
            [athlete.targetresult_set.create(event_id=event_id, apparatus_id=i, target_sv=0,\
                target_ex=0, result_sv=0, result_ex=0) for i in range(1, 7)]
        # Female apparatus: 1=floor, 4=vault, 7=uneven bars, 8=balance beam
        elif athlete.gender == 2:
            [athlete.targetresult_set.create(event_id=event_id, apparatus_id=i, target_sv=0,\
                target_ex=0, result_sv=0, result_ex=0) for i in [1,4,7,8]] 
    return redirect(reverse('board:athlete-detail', args=[athlete_id]))

@login_required
def athlete_update_target(request, athlete_id):
    if request.is_ajax and request.method == "POST":
        event_id = request.POST.get('event_id', None)
        apparatus_id = request.POST.get('apparatus_id', None)
        target_result = TargetResult.objects.get(athlete__id=athlete_id, event__id=event_id, \
                                                      apparatus__id=apparatus_id)
        target_result.target_sv = request.POST.get('tsv', None)
        target_result.target_ex = request.POST.get('tex', None)
        target_result.result_sv = request.POST.get('rsv', None)
        target_result.result_ex = request.POST.get('rex', None)

    # athlete_event = AthleteEvent.query.filter_by(athlete_id=id, \
    #                                              event_id=event_id).first()
    # athlete_event.target_total = request.form['target']
    # athlete_event.result_total = request.form['result']
    target_result.save()
    data = {
        'success': 'success'
    }
    return JsonResponse(data)

@login_required
def athlete_save_information(request, athlete_id):
    # injury and comment are both a TypeInformation
    # (foreign key of Information table)
    athlete = get_object_or_404(Athlete, pk=athlete_id)
    if request.method == 'POST':
        form = SaveInformationForm(request.POST)
        if form.is_valid():
            # Get TypeInformation object include in input:hidden
            ty = TypeInformation.objects.get(\
                name=form.cleaned_data.get('information_type'))
            # Check if it's an edit or a new information
            if form.cleaned_data.get('information_id') == 'new':
                Information.objects.create(
                    body=form.cleaned_data.get('body'),
                    athlete=athlete,
                    author=request.user,
                    type=ty,
                    )
            else:
                info = Information.objects.get(\
                        pk=form.cleaned_data.get('information_id'))
                # Only the author can edit its information
                if info.author == request.user:
                    info.body = form.cleaned_data.get('body')
                    # info.timestamp = timezone.now()
                    info.save()
    return redirect('board:athlete-detail', athlete_id=athlete_id)

def athlete_graph_get_data(request, athlete_id):
    labels = []
    targets_list = []
    results_list = []
    success = []

    queryset = TargetResult.objects.filter(athlete__id=athlete_id).values(\
        'event__name').annotate(target_total=Round2(Sum('target_sv') + Sum('target_ex'), 2),
                                result_total=Round2(Sum('result_sv') + Sum('result_ex'), 2), 
                                success=Round2(F('result_total') / F('target_total') * 100, 2))
    for entry in queryset:
        labels.append(entry['event__name'])
        targets_list.append(entry['target_total'])
        results_list.append(entry['result_total'])
        success.append(entry['success'])
    
    return JsonResponse(data={
        'labels': labels,
        'targets': targets_list,
        'results': results_list,
        'success': success
    })

managym-app/board/templates/board/_content_comments_tab.html
<button type="button" class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#save-comment">{{ _('Add comment') }}</button>

{% with athlete.comments as information_all %} 
{% if information_all %}
<table class="table table-hover">
  <tbody>
  {% for information in information_all %}
    <tr data-info-id="{{ information.id }}">
      <td class="col-sm-11">
        <p>
          <b>{{ information.author.first_name }} {{ information.author.last_name }}
            - {{ information.timestamp }}:</b>
        <p>
        <div class="information-body">
          {{ information.get_body_as_markdown|linebreaks }}
        <div>
      </td>
      <td class="col-sm-1 text-right">
          <!-- Call to action buttons -->
        {% if information.author == user %}
        <button type="button" class="btn btn-sm rounded-0 btn-edit" data-toggle="modal" data-target="#save-comment" data-information-id="{{ information.pk }}" data-information-body="{{ information.body }}"><i class="fas fa-edit"></i></button> 
        {% endif %}
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% else %}
<br>  
<h3 class="text-center">{{ _('This athlete has no comment yet.') }}</h3> 
{% endif %}
{% endwith %}

<div class="modal fade" id="save-comment" tabindex="-1" role="dialog" aria-labelledby="new-information" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">{{ _('New comment') }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" action="{% url 'board:athlete-save-information' athlete.pk %}" novalidate>
      <div class="modal-body">
		    {% csrf_token %}
		    {{ new_information_form.non_field_errors }}
				<div class="fieldWrapper">
			    {{ new_information_form.body.errors }}
          <div class="form-group">
			      {{ new_information_form.body }}
          </div>
				</div>
        {{ new_information_form.information_id }}
        {{ new_information_form.information_type }}
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">{{ _('Save comment') }}</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ _('Close') }}</button>
      </div>
		 	</form>
    </div>
  </div>
</div>

managym-app/board/templates/board/_content_injuries_tab.html
<button type="button" class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#save-injury">{{ _('Add injury') }}</button>

{% with athlete.injuries as information_all %} 
{% if information_all %}
<table class="table table-hover">
	<tbody>
  {% for information in information_all %}
    <tr data-info-id="{{ information.id }}">
      <td class="col-sm-11">
        <p>
          <b>{{ information.author.first_name }} {{ information.author.last_name }}
            - {{ information.timestamp }}:</b>
        <p>
        <div class="information-body">
          {{ information.get_body_as_markdown }}
        <div>
      </td>
      <td class="col-sm-1 text-right">
          <!-- Call to action buttons -->
        {% if information.author == user %}
        <button type="button" class="btn btn-sm rounded-0 btn-edit" data-toggle="modal" data-target="#save-injury" data-information-id="{{ information.pk }}" data-information-body="{{ information.body }}"><i class="fas fa-edit"></i></button>
        {% endif %}
      </td>
    </tr>
  {% endfor %}
	</tbody>
</table>
{% else %}
<br>  
<h3 class="text-center">{{ _('This athlete has no injury yet.') }}</h3> 
{% endif %}
{% endwith %}

<div class="modal fade" id="save-injury" tabindex="-1" role="dialog" aria-labelledby="new-injury" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">{{ _('New injury') }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" action="{% url 'board:athlete-save-information' athlete.pk %}" novalidate>
      <div class="modal-body">
		    {% csrf_token %}
		    {{ new_information_form.non_field_errors }}
				<div class="fieldWrapper">
			    {{ new_information_form.body.errors }}
          <div class="form-group">
			      {{ new_information_form.body }}
          </div>
				</div>
        {{ new_information_form.information_id }}
        {{ new_information_form.information_type }}
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">{{ _('Save injury') }}</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ _('Close') }}</button>
      </div>
		 	</form>
    </div>
  </div>
</div>

managym-app/board/templates/board/_content_target_tab.html
{% load static %}
<div class="row">
  <div class="col-6">
  {% if new_target_form.event.field.choices.queryset|length %}
    <form action="{% url 'board:athlete-new-target' athlete_id=athlete.pk %}" method="post" class="form-inline">
      {% csrf_token %}
      {{ new_target_form.non_field_errors }}
      <div class="fieldWrapper">
        {{ new_target_form.event.errors }}
        {{ new_target_form.event }}
      </div>
      <input type="submit" value="Add target" class="btn btn-primary">
    </form> 
  {% endif %}
  </div>
  {% if events_participated %}
  <div class="col-6 text-right">
    <button id="btn-graphs" class="btn btn-warning" data-toggle="modal" data-target="#modLineChart" data-url="{% url 'board:athlete-graph-get-data' athlete.id %}">{{ _('Graph of events') }}</button>
  </div>
  {% include "board/athlete-graph.html" %}
  {% endif %}
</div>

{% if events_participated %}
<div class="accordion" id="accordionTargetResults" data-update-target-url={% url 'board:athlete-update-target' athlete.id %}>
  {% for event in events_participated %}
  <div class="card">
    <div class="card-header" id="headingEvent{{ event.id }}">
      <h2 class="mb-0">
        <button class="btn btn-link btn-lg text-left" type="button" data-toggle="collapse" data-target="#collapseEvent{{ event.id }}" 
        aria-expanded="alse" aria-controls="collapseEvent{{ event.id }}">
          {{ event.name }} - {{ event.date|date:'Y' }}
        </button>
      </h2>
    </div>

    <div id="collapseEvent{{ event.id }}" class="collapse" aria-labelledby="headingEvent{{ event.id }}" data-parent="#accordionTargetResults">
      <div class="card-body">
        {% include "board/_target_table.html" %}  
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% else %}
  <p>{{ _("There is no target for this athlete.") }}</p>
{% endif %}

managym-app/board/templates/board/_information.html
<tr data-info-id="{{ information.id }}">
	<td class="col-sm-11">
		<p>
			<b>{{ information.author.first_name }} {{ information.author.last_name }}
				- {{ information.timestamp }}:</b>
		<p>
		<div>
	  	{{ information.body }}
		<div>
	</td>
	<td class="col-sm-1 text-right">
	    <!-- Call to action buttons -->
	 <button class="btn btn-sm rounded-0 btn-edit" type="button" data-toggle="tooltip" data-placement="top" title="Edit"><i class="fas fa-edit"></i></button>
 	  <!--<ul class="list-inline">
	        <li>
	            <button class="btn btn-sm rounded-0 btn-edit" type="button" data-toggle="tooltip" data-placement="top" title="Edit"><i class="fas fa-edit"></i></button>
	        </li>
	        <li>
	            <button class="btn btn-danger btn-sm rounded-0 btn-delete" type="button" data-toggle="tooltip" data-placement="top" title="Delete"><i class="fas fa-trash"></i></button>
	        </li>
	    </ul> -->
	</td>
</tr>

managym-app/board/templates/board/_target_table.html
<div class="table-responsive">
	<table class="table table-bordered target-results">
		<thead>
			<tr>
				<th scope="col">Apparatus</th>
				<th scope="col" colspan="3">Target</th>
				<th scope="col" colspan="6">Results</th>
			</tr>
			<tr class="active">
				<th scope="col"></th>
				<th scope="col">SV</th>
				<th scope="col">E</th>
				<th scope="col">Score</th>
				<th scope="col">SV</th>
				<th scope="col">target (%)</th>
				<th scope="col">E</th>
				<th scope="col">target (%)</th>
				<th scope="col">Score</th>
				<th scope="col">target (%)</th>
			</tr>
		</thead>
		<tbody>
			{% for target in event.targets_results %}
			<tr class="apparatus {{ target.apparatus__id}}">
				<th class="active">{{ target.apparatus__name }}</th>
				<td class="tsv" contenteditable="True">{{ target.target_sv }}</td>
				<td class="tex" contenteditable="True">{{ target.target_ex }}</td>
				<td class="ttot total-color"></td>
				<td class="rsv" contenteditable="True">{{ target.result_sv }}</td>
				<td class="trsv active percentage-score"></td>
				<td class="rex" contenteditable="True">{{ target.result_ex }}</td>
				<td class="trex active percentage-score"></td>
				<td class="rtot total-color"></td>
				<td class="trtot active percentage-score"></td>
			</tr>
			{% endfor %}
			<tr class="total-event active total-color">
				<th>{{ _('Total') }}</th>
				<td class="tsvtot"></td>
				<td class="textot"></td>
				<td class="target-total"></td>
				<td class="rsvtot"></td>
				<td class="trsvtot"></td>
				<td class="rextot"></td>
				<td class="trextot"></td>
				<td class="result-total"></td>
				<td class="target-result-total"></td>
			</tr>	
		</tbody>
	</table>
</div>

managym-app/board/templates/board/athlete-graph.html
<div class="modal fade" id="modLineChart" tabindex="-1" role="dialog" aria-labelledby="modLineChartLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modLineChartLabel">{{ _("Graph of targets and results of all events") }}</h4>
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                </button>
            </div>
            <div class="modal-body">
                <canvas id="myLineChart" width="800" height="450"></canvas>
            </div>
        </div>
    </div>
</div>

managym-app/board/templates/board/athlete.html
{% extends "base.html" %}
{% load static %}

{% block title %}Athlete detail - Managym{% endblock title %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'board/css/athlete.css' %}" />
{% endblock %}

{% block javascript %}
  <script src="{% static 'board/js/athleteTarget.js' %}"></script>
  <script src="{% static 'board/js/athleteGraph.js' %}"></script>
{% endblock  %}

{% block content %}
  <!-- Profile of the athlete -->
<br>	  
<div class="row">
  <div class="col-md-3 text-center">
    <img src="{{ athlete.picture }}"> 
  </div>
  <div class="col-md-9">
    <table class="table table-sm table-borderless">
      <tr>
        <td colspan="2">
            <h1>{{ athlete.first_name|title }} {{ athlete.last_name|title }}</h1>
        </td>
      </tr>
      <tr>
        <td>
            {{ _('Date of birth: ') }}<b>{{ athlete.birth_date }}</b>
        </td>
        <td>
            {{ _('Gender: ') }}<b>{{ athlete.gend|title }}</b>
        </td>
      </tr>
      <tr>
        <td>
          {{ _('Phone number 1: ') }}<b>{{ athlete.phone_number }}</b>
        </td>
        <td>
          {{ _('Email 1: ') }}<b>{{ athlete.email }}</b>
        </td>
      </tr>
      <tr>
        <td>
          {{ _('Phone number 2: ') }}<b>{{ athlete.phone_number_2 }}</b>
        </td>
        <td>
          {{ _('Email 2: ') }}<b>{{ athlete.email_2 }}</b>
        </td>
      </tr>
      {% if athlete.group %}
      <tr>
        <td colspan="2">
          {{ _('Group: ') }}<b>{{ athlete.group.name }}</b>
        </td>
      {% endif %}
      </tr>
    </table>
  </div> 
</div>

<!-- Nav tab -->
<ul class="nav nav-tabs" id="athlete-tabs" role="tablist">
  <li class="nav-item">
    <a class="nav-link" id="targets-tab" data-toggle="tab" href="#targets-content" role="tab" aria-controls="targets" aria-selected="false">Targets</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="injuries-tab" data-toggle="tab" href="#injuries-content" role="tab" aria-controls="injuries" aria-selected="false">Injuries</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="comments-tab" data-toggle="tab" href="#comments-content" role="tab" aria-controls="comments" aria-selected="false">Comments</a>
  </li>
</ul>
<div class="tab-content" id="athlete-tabsContent">
  <div class="tab-pane fade active" id="targets-content" role="tabpanel" aria-labelledby="targets-tab">
    {% include "board/_content_target_tab.html" %}
  </div>
  <div class="tab-pane fade" id="injuries-content" role="tabpanel" aria-labelledby="injuries-tab">
    {# {% include "athlete/_content_injuries_tab.html" %} #}
  </div>
  <div class="tab-pane fade" id="comments-content" role="tabpanel" aria-labelledby="comments-tab">
     {# {% include "" %} #}
  </div>
</div>
{% endblock %}

managym-app/board/templates/board/board.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <div class="col-12">
      <h1>{{ _('Hello') }} {{ user.first_name }}</h1> 
    </div>
    {% if athletes %}
    <br>
    <div class="table-responsive">
      <table class="table table-hover text-center">
        <thead class="thead-dark">
          <tr>
            <th scope="col" class="text-center">{{ _('First') }}</th>
            <th scope="col" class="text-center">{{ _('Last') }}</th>
            <th scope="col" class="text-center">{{ _('Date of birth') }}</th>
            <th scope="col" class="text-center">{{ _('Phone') }}</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        {% for athlete in athletes %}
            <tr>
              <td>{{ athlete.first_name }}</td>
              <td>{{ athlete.last_name }}</td>
              <td>{{ athlete.birth_date }}</td>
              <td>{{ athlete.phone_number }}</td>
              <td>
                <a href="{% url 'board:athlete-detail' athlete.id %}"><i class="fas fa-user"></i> {{ _('Profile') }}</a>
              </td>
            </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
    {% if is_paginated %}
      {% include "board/pagination.html" %}
    {% endif %}
    {% else %}
    <div>
      <h4>{{ _('You have no athlete in your group.') }}</h4>
    </div>
    {% endif %}
  </div>
{% endblock %}